[package]
name = "static_index"
version = "0.1.0"
authors = ["Jose Marinez <digeratus@gmail.com>"]

[dependencies]
futures = "0.1"
env_logger = "0.5"
actix = "^0.5.5"
actix-web = { git="https://github.com/actix/actix-web.git" }

[workspace]
members = [
  "./"
]